name: hydr_leak_tracker
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+3

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.1
  flutter_riverpod: ^2.1.3
  mockito: ^5.3.2
  path: ^1.8.2
  path_provider: ^2.0.12
  intl: ^0.18.0
  shared_preferences: ^2.0.17
  fl_chart: ^0.60.0
  scrollable_positioned_list: ^0.3.5
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
