name: win release
on: workflow_dispatch

jobs:
  build:
    name: flutter release
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            flutter-version: '3.7.0'
        - name: Install project dependencies
          run: flutter pub get
        - name: Generate intermediates
          run: flutter pub run build_runner build --delete-conflicting-outputs
        - name: Enable windows build
          run: flutter config --enable-windows-desktop
        - name: Build artifacts
          run: flutter build windows --release
        - name: Archive Release
          uses: thedoctor0/zip-release@master
          with:
            type: 'zip'
            filename: HydrLeakTracker-${{github.ref_name}}-windows.zip
            directory: build/windows/runner/Release
        - name: Windows Release
          uses: actions/upload-artifact@v1
          with:
            name: HydrLeakTracker-${{github.ref_name}}-windows.zip
            files: build/windows/runner/Release/HydrLeakTracker-${{github.ref_name}}-windows.zip
